# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motionlist',
            old_name='name',
            new_name='list_name',
        ),
    ]
