# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_motion_motion_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motionlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='motionlist',
            name='list_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
