# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0004_auto_20170423_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customize',
            name='file_path',
            field=models.FilePathField(),
        ),
    ]
